<?php

namespace DoctrineHydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

use function array_key_exists;
use function gettype;
use function is_array;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentsWorkFlowTemplateHydrator implements HydratorInterface
{
    public function __construct(private DocumentManager $dm, private ClassMetadata $class) {}

    public function hydrate(object $document, array $data, array $hints = []): array
    {
        $hydratedData = [];

        // Field(type: "id")
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        // Field(type: "string")
        if (isset($data['name']) || (! empty($this->class->fieldMappings['name']['nullable']) && array_key_exists('name', $data))) {
            $value = $data['name'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['name']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        // Field(type: "string")
        if (isset($data['code']) || (! empty($this->class->fieldMappings['code']['nullable']) && array_key_exists('code', $data))) {
            $value = $data['code'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['code']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['code']->setValue($document, $return);
            $hydratedData['code'] = $return;
        }

        // Field(type: "string")
        if (isset($data['description']) || (! empty($this->class->fieldMappings['description']['nullable']) && array_key_exists('description', $data))) {
            $value = $data['description'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['description']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['is_active']) || (! empty($this->class->fieldMappings['is_active']['nullable']) && array_key_exists('is_active', $data))) {
            $value = $data['is_active'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['is_active']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['is_active']->setValue($document, $return);
            $hydratedData['is_active'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['is_default']) || (! empty($this->class->fieldMappings['is_default']['nullable']) && array_key_exists('is_default', $data))) {
            $value = $data['is_default'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['is_default']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['is_default']->setValue($document, $return);
            $hydratedData['is_default'] = $return;
        }

        // ReferenceOne
        if (isset($data['created_by']) || (! empty($this->class->fieldMappings['created_by']['nullable']) && array_key_exists('created_by', $data))) {
            $return = $data['created_by'];
            if ($return !== null) {
                if ($this->class->fieldMappings['created_by']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\WorkFlowTemplate', 'created_by', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['created_by'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['created_by']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['created_by']->setValue($document, $return);
            $hydratedData['created_by'] = $return;
        }

        // ReferenceOne
        if (isset($data['updated_by']) || (! empty($this->class->fieldMappings['updated_by']['nullable']) && array_key_exists('updated_by', $data))) {
            $return = $data['updated_by'];
            if ($return !== null) {
                if ($this->class->fieldMappings['updated_by']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\WorkFlowTemplate', 'updated_by', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['updated_by'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['updated_by']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['updated_by']->setValue($document, $return);
            $hydratedData['updated_by'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('created_at', $data) && ($data['created_at'] !== null || ($this->class->fieldMappings['created_at']['nullable'] ?? false))) {
            $value = $data['created_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['created_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['created_at'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('updated_at', $data) && ($data['updated_at'] !== null || ($this->class->fieldMappings['updated_at']['nullable'] ?? false))) {
            $value = $data['updated_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['updated_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['updated_at'] = $return;
        }

        return $hydratedData;
    }
}