<?php

namespace DoctrineHydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

use function array_key_exists;
use function gettype;
use function is_array;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentsWorkFlowStagesHydrator implements HydratorInterface
{
    public function __construct(private DocumentManager $dm, private ClassMetadata $class) {}

    public function hydrate(object $document, array $data, array $hints = []): array
    {
        $hydratedData = [];

        // Field(type: "id")
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        // ReferenceOne
        if (isset($data['workflow_template']) || (! empty($this->class->fieldMappings['workflow_template']['nullable']) && array_key_exists('workflow_template', $data))) {
            $return = $data['workflow_template'];
            if ($return !== null) {
                if ($this->class->fieldMappings['workflow_template']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\WorkFlowStages', 'workflow_template', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['workflow_template'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['workflow_template']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['workflow_template']->setValue($document, $return);
            $hydratedData['workflow_template'] = $return;
        }

        // Field(type: "string")
        if (isset($data['stage_name']) || (! empty($this->class->fieldMappings['stage_name']['nullable']) && array_key_exists('stage_name', $data))) {
            $value = $data['stage_name'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['stage_name']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['stage_name']->setValue($document, $return);
            $hydratedData['stage_name'] = $return;
        }

        // Field(type: "int")
        if (isset($data['stage_order']) || (! empty($this->class->fieldMappings['stage_order']['nullable']) && array_key_exists('stage_order', $data))) {
            $value = $data['stage_order'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['stage_order']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['stage_order']->setValue($document, $return);
            $hydratedData['stage_order'] = $return;
        }

        // ReferenceOne
        if (isset($data['department']) || (! empty($this->class->fieldMappings['department']['nullable']) && array_key_exists('department', $data))) {
            $return = $data['department'];
            if ($return !== null) {
                if ($this->class->fieldMappings['department']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\WorkFlowStages', 'department', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['department'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['department']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['department']->setValue($document, $return);
            $hydratedData['department'] = $return;
        }

        // ReferenceOne
        if (isset($data['role']) || (! empty($this->class->fieldMappings['role']['nullable']) && array_key_exists('role', $data))) {
            $return = $data['role'];
            if ($return !== null) {
                if ($this->class->fieldMappings['role']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\WorkFlowStages', 'role', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['role'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['role']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['role']->setValue($document, $return);
            $hydratedData['role'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['can_skip']) || (! empty($this->class->fieldMappings['can_skip']['nullable']) && array_key_exists('can_skip', $data))) {
            $value = $data['can_skip'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['can_skip']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['can_skip']->setValue($document, $return);
            $hydratedData['can_skip'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['can_rework']) || (! empty($this->class->fieldMappings['can_rework']['nullable']) && array_key_exists('can_rework', $data))) {
            $value = $data['can_rework'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['can_rework']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['can_rework']->setValue($document, $return);
            $hydratedData['can_rework'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['is_mandatory']) || (! empty($this->class->fieldMappings['is_mandatory']['nullable']) && array_key_exists('is_mandatory', $data))) {
            $value = $data['is_mandatory'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['is_mandatory']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['is_mandatory']->setValue($document, $return);
            $hydratedData['is_mandatory'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['is_final_stage']) || (! empty($this->class->fieldMappings['is_final_stage']['nullable']) && array_key_exists('is_final_stage', $data))) {
            $value = $data['is_final_stage'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['is_final_stage']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['is_final_stage']->setValue($document, $return);
            $hydratedData['is_final_stage'] = $return;
        }

        // Field(type: "float")
        if (isset($data['sla_hours']) || (! empty($this->class->fieldMappings['sla_hours']['nullable']) && array_key_exists('sla_hours', $data))) {
            $value = $data['sla_hours'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['sla_hours']['type'];
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['sla_hours']->setValue($document, $return);
            $hydratedData['sla_hours'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['is_active']) || (! empty($this->class->fieldMappings['is_active']['nullable']) && array_key_exists('is_active', $data))) {
            $value = $data['is_active'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['is_active']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['is_active']->setValue($document, $return);
            $hydratedData['is_active'] = $return;
        }

        // ReferenceOne
        if (isset($data['created_by']) || (! empty($this->class->fieldMappings['created_by']['nullable']) && array_key_exists('created_by', $data))) {
            $return = $data['created_by'];
            if ($return !== null) {
                if ($this->class->fieldMappings['created_by']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\WorkFlowStages', 'created_by', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['created_by'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['created_by']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['created_by']->setValue($document, $return);
            $hydratedData['created_by'] = $return;
        }

        // ReferenceOne
        if (isset($data['updated_by']) || (! empty($this->class->fieldMappings['updated_by']['nullable']) && array_key_exists('updated_by', $data))) {
            $return = $data['updated_by'];
            if ($return !== null) {
                if ($this->class->fieldMappings['updated_by']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\WorkFlowStages', 'updated_by', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['updated_by'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['updated_by']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['updated_by']->setValue($document, $return);
            $hydratedData['updated_by'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('created_at', $data) && ($data['created_at'] !== null || ($this->class->fieldMappings['created_at']['nullable'] ?? false))) {
            $value = $data['created_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['created_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['created_at'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('updated_at', $data) && ($data['updated_at'] !== null || ($this->class->fieldMappings['updated_at']['nullable'] ?? false))) {
            $value = $data['updated_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['updated_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['updated_at'] = $return;
        }

        return $hydratedData;
    }
}