<?php

namespace DoctrineHydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

use function array_key_exists;
use function gettype;
use function is_array;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentsUserHydrator implements HydratorInterface
{
    public function __construct(private DocumentManager $dm, private ClassMetadata $class) {}

    public function hydrate(object $document, array $data, array $hints = []): array
    {
        $hydratedData = [];

        // Field(type: "id")
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        // Field(type: "string")
        if (isset($data['name']) || (! empty($this->class->fieldMappings['name']['nullable']) && array_key_exists('name', $data))) {
            $value = $data['name'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['name']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        // Field(type: "string")
        if (isset($data['email']) || (! empty($this->class->fieldMappings['email']['nullable']) && array_key_exists('email', $data))) {
            $value = $data['email'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['email']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['email']->setValue($document, $return);
            $hydratedData['email'] = $return;
        }

        // Field(type: "string")
        if (isset($data['mobile_no']) || (! empty($this->class->fieldMappings['mobile_no']['nullable']) && array_key_exists('mobile_no', $data))) {
            $value = $data['mobile_no'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['mobile_no']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['mobile_no']->setValue($document, $return);
            $hydratedData['mobile_no'] = $return;
        }

        // Field(type: "string")
        if (isset($data['username']) || (! empty($this->class->fieldMappings['username']['nullable']) && array_key_exists('username', $data))) {
            $value = $data['username'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['username']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['username']->setValue($document, $return);
            $hydratedData['username'] = $return;
        }

        // Field(type: "string")
        if (isset($data['password']) || (! empty($this->class->fieldMappings['password']['nullable']) && array_key_exists('password', $data))) {
            $value = $data['password'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['password']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['password']->setValue($document, $return);
            $hydratedData['password'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['is_active']) || (! empty($this->class->fieldMappings['is_active']['nullable']) && array_key_exists('is_active', $data))) {
            $value = $data['is_active'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['is_active']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['is_active']->setValue($document, $return);
            $hydratedData['is_active'] = $return;
        }

        // ReferenceOne
        if (isset($data['role']) || (! empty($this->class->fieldMappings['role']['nullable']) && array_key_exists('role', $data))) {
            $return = $data['role'];
            if ($return !== null) {
                if ($this->class->fieldMappings['role']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\User', 'role', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['role'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['role']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['role']->setValue($document, $return);
            $hydratedData['role'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('created_at', $data) && ($data['created_at'] !== null || ($this->class->fieldMappings['created_at']['nullable'] ?? false))) {
            $value = $data['created_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['created_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['created_at'] = $return;
        }

        return $hydratedData;
    }
}