<?php

namespace DoctrineHydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

use function array_key_exists;
use function gettype;
use function is_array;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentsTaskHydrator implements HydratorInterface
{
    public function __construct(private DocumentManager $dm, private ClassMetadata $class) {}

    public function hydrate(object $document, array $data, array $hints = []): array
    {
        $hydratedData = [];

        // Field(type: "id")
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        // Field(type: "string")
        if (isset($data['task_code']) || (! empty($this->class->fieldMappings['task_code']['nullable']) && array_key_exists('task_code', $data))) {
            $value = $data['task_code'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['task_code']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['task_code']->setValue($document, $return);
            $hydratedData['task_code'] = $return;
        }

        // Field(type: "string")
        if (isset($data['title']) || (! empty($this->class->fieldMappings['title']['nullable']) && array_key_exists('title', $data))) {
            $value = $data['title'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['title']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        // Field(type: "string")
        if (isset($data['description']) || (! empty($this->class->fieldMappings['description']['nullable']) && array_key_exists('description', $data))) {
            $value = $data['description'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['description']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        // ReferenceMany
        $mongoData = $data['attachments'] ?? null;

        if ($mongoData !== null && ! is_array($mongoData)) {
            throw HydratorException::associationTypeMismatch('App\Documents\Task', 'attachments', 'array', gettype($mongoData));
        }

        $return = $this->dm->getConfiguration()->getPersistentCollectionFactory()->create($this->dm, $this->class->fieldMappings['attachments']);
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['attachments']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->propertyAccessors['attachments']->setValue($document, $return);
        $hydratedData['attachments'] = $return;

        // ReferenceOne
        if (isset($data['project_id']) || (! empty($this->class->fieldMappings['project']['nullable']) && array_key_exists('project_id', $data))) {
            $return = $data['project_id'];
            if ($return !== null) {
                if ($this->class->fieldMappings['project']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\Task', 'project_id', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['project'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['project']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['project']->setValue($document, $return);
            $hydratedData['project'] = $return;
        }

        // ReferenceOne
        if (isset($data['current_department_id']) || (! empty($this->class->fieldMappings['current_department']['nullable']) && array_key_exists('current_department_id', $data))) {
            $return = $data['current_department_id'];
            if ($return !== null) {
                if ($this->class->fieldMappings['current_department']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\Task', 'current_department_id', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['current_department'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['current_department']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['current_department']->setValue($document, $return);
            $hydratedData['current_department'] = $return;
        }

        // ReferenceOne
        if (isset($data['current_assignee_id']) || (! empty($this->class->fieldMappings['current_assignee']['nullable']) && array_key_exists('current_assignee_id', $data))) {
            $return = $data['current_assignee_id'];
            if ($return !== null) {
                if ($this->class->fieldMappings['current_assignee']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\Task', 'current_assignee_id', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['current_assignee'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['current_assignee']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['current_assignee']->setValue($document, $return);
            $hydratedData['current_assignee'] = $return;
        }

        // ReferenceOne
        if (isset($data['workflow_template_id']) || (! empty($this->class->fieldMappings['workflow_template']['nullable']) && array_key_exists('workflow_template_id', $data))) {
            $return = $data['workflow_template_id'];
            if ($return !== null) {
                if ($this->class->fieldMappings['workflow_template']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\Task', 'workflow_template_id', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['workflow_template'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['workflow_template']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['workflow_template']->setValue($document, $return);
            $hydratedData['workflow_template'] = $return;
        }

        // ReferenceOne
        if (isset($data['current_workflow_stage_id']) || (! empty($this->class->fieldMappings['current_workflow_stage']['nullable']) && array_key_exists('current_workflow_stage_id', $data))) {
            $return = $data['current_workflow_stage_id'];
            if ($return !== null) {
                if ($this->class->fieldMappings['current_workflow_stage']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\Task', 'current_workflow_stage_id', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['current_workflow_stage'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['current_workflow_stage']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['current_workflow_stage']->setValue($document, $return);
            $hydratedData['current_workflow_stage'] = $return;
        }

        // Field(type: "string")
        if (isset($data['execution_status']) || (! empty($this->class->fieldMappings['execution_status']['nullable']) && array_key_exists('execution_status', $data))) {
            $value = $data['execution_status'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['execution_status']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['execution_status']->setValue($document, $return);
            $hydratedData['execution_status'] = $return;
        }

        // Field(type: "string")
        if (isset($data['priority']) || (! empty($this->class->fieldMappings['priority']['nullable']) && array_key_exists('priority', $data))) {
            $value = $data['priority'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['priority']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['priority']->setValue($document, $return);
            $hydratedData['priority'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('started_at', $data) && ($data['started_at'] !== null || ($this->class->fieldMappings['started_at']['nullable'] ?? false))) {
            $value = $data['started_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['started_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['started_at'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('due_at', $data) && ($data['due_at'] !== null || ($this->class->fieldMappings['due_at']['nullable'] ?? false))) {
            $value = $data['due_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['due_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['due_at'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('completed_at', $data) && ($data['completed_at'] !== null || ($this->class->fieldMappings['completed_at']['nullable'] ?? false))) {
            $value = $data['completed_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['completed_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['completed_at'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('original_due_at', $data) && ($data['original_due_at'] !== null || ($this->class->fieldMappings['original_due_at']['nullable'] ?? false))) {
            $value = $data['original_due_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['original_due_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['original_due_at'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('current_hold_started_at', $data) && ($data['current_hold_started_at'] !== null || ($this->class->fieldMappings['current_hold_started_at']['nullable'] ?? false))) {
            $value = $data['current_hold_started_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['current_hold_started_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['current_hold_started_at'] = $return;
        }

        // Field(type: "int")
        if (isset($data['total_hold_duration_seconds']) || (! empty($this->class->fieldMappings['total_hold_duration_seconds']['nullable']) && array_key_exists('total_hold_duration_seconds', $data))) {
            $value = $data['total_hold_duration_seconds'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['total_hold_duration_seconds']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['total_hold_duration_seconds']->setValue($document, $return);
            $hydratedData['total_hold_duration_seconds'] = $return;
        }

        // Field(type: "bool")
        if (isset($data['is_sla_breached']) || (! empty($this->class->fieldMappings['is_sla_breached']['nullable']) && array_key_exists('is_sla_breached', $data))) {
            $value = $data['is_sla_breached'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['is_sla_breached']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['is_sla_breached']->setValue($document, $return);
            $hydratedData['is_sla_breached'] = $return;
        }

        // Field(type: "int")
        if (isset($data['sla_breach_count']) || (! empty($this->class->fieldMappings['sla_breach_count']['nullable']) && array_key_exists('sla_breach_count', $data))) {
            $value = $data['sla_breach_count'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['sla_breach_count']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->propertyAccessors['sla_breach_count']->setValue($document, $return);
            $hydratedData['sla_breach_count'] = $return;
        }

        // ReferenceOne
        if (isset($data['created_by']) || (! empty($this->class->fieldMappings['created_by']['nullable']) && array_key_exists('created_by', $data))) {
            $return = $data['created_by'];
            if ($return !== null) {
                if ($this->class->fieldMappings['created_by']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\Task', 'created_by', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['created_by'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['created_by']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['created_by']->setValue($document, $return);
            $hydratedData['created_by'] = $return;
        }

        // ReferenceOne
        if (isset($data['updated_by']) || (! empty($this->class->fieldMappings['updated_by']['nullable']) && array_key_exists('updated_by', $data))) {
            $return = $data['updated_by'];
            if ($return !== null) {
                if ($this->class->fieldMappings['updated_by']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($return)) {
                    throw HydratorException::associationTypeMismatch('App\Documents\Task', 'updated_by', 'array', gettype($return));
                }

                $className = $this->dm->getClassNameForAssociation($this->class->fieldMappings['updated_by'], $return);
                $identifier = ClassMetadata::getReferenceId($return, $this->class->fieldMappings['updated_by']['storeAs']);
                $targetMetadata = $this->dm->getClassMetadata($className);
                $id = $targetMetadata->getPHPIdentifierValue($identifier);
                $return = $this->dm->getReference($className, $id);
            }

            $this->class->propertyAccessors['updated_by']->setValue($document, $return);
            $hydratedData['updated_by'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('created_at', $data) && ($data['created_at'] !== null || ($this->class->fieldMappings['created_at']['nullable'] ?? false))) {
            $value = $data['created_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['created_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['created_at'] = $return;
        }

        // Field(type: "date")
        if (array_key_exists('updated_at', $data) && ($data['updated_at'] !== null || ($this->class->fieldMappings['updated_at']['nullable'] ?? false))) {
            $value = $data['updated_at'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->propertyAccessors['updated_at']->setValue($document, $return === null ? null : clone $return);
            $hydratedData['updated_at'] = $return;
        }

        return $hydratedData;
    }
}